FROM python:3.12-slim

WORKDIR /app

COPY src/requirements.txt .

# CREPE needs a verrrrry specific setup tools to work
RUN pip install --no-cache-dir "setuptools<81" 

# Install everything except crepe normally
RUN pip install --no-cache-dir -r requirements.txt

# Install old CREPE (love this phrasing)
RUN pip install --no-cache-dir --no-build-isolation "crepe==0.0.16"

COPY src/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8060"]