# from this tutorial: https://thedkpatel.medium.com/dockerizing-react-application-built-with-vite-a-simple-guide-4c41eb09defa
FROM node:18-alpine

WORKDIR /app/src

COPY src/package.json .

RUN npm install

RUN npm i -g serve

COPY . .

RUN npm run build

EXPOSE 3005

CMD [ "serve", "-s", "dist" ]