# from this tutorial: https://thedkpatel.medium.com/dockerizing-react-application-built-with-vite-a-simple-guide-4c41eb09defa
FROM node:22-alpine

WORKDIR /app

COPY src/package*.json ./

RUN npm install

COPY src/ ./

RUN npm run build

RUN npm install -g serve

EXPOSE 3005

CMD ["serve", "-s", "dist", "-l", "3005"]