services:
  frontend:
    build:
      context: ./frontend/
    networks:
      - frontend-network
    ports:
      - "3005:3005"

  api:
    build:
      context: ./backend/api/
    networks:
      - model-network
      - frontend-network
    ports:
      - "8070:8070"

  text-to-music:
    build:
      context: ./backend/text-to-music
    networks:
      - model-network
    ports:
      - "8080:8080"
    environment:
      - "GIT_PYTHON_REFRESH: quiet"

  basic-pitch:
    build:
      context: ./backend/basic-pitch
    networks:
      - model-network
    ports:
      - "8090:8090"
    environment:
      - "GIT_PYTHON_REFRESH: quiet"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.5
    ports:
      - "5050:5050"
    networks:
      - model-network
    volumes:
      - mlflow_data:/mlflow
    # Command to start the server inside the container, pointing to local storage
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5050 
      --backend-store-uri sqlite:////mlflow/mlflow.db 
      --default-artifact-root /mlflow/artifacts

networks:
  frontend-network:
    driver: bridge

  model-network:
    driver: bridge

volumes:
  mlflow_data:
