FROM python:3.12-slim

WORKDIR /app

# install required libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libffi-dev \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# get rust/cargo
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# add rust to path
ENV PATH="/root/.cargo/bin:${PATH}"

# tell rust to shut up and allow to me do old things
ENV RUSTFLAGS="-A invalid_reference_casting"

COPY src/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
